package io.github.kensuke1984.kibrary.inversion.addons;

public enum CombinationType {
	CORRIDOR_BOXCAR, CORRIDOR_TRIANGLE, LOWERMANTLE_BOXCAR_3D, TRANSITION_ZONE_23, TRANSITION_ZONE_20, TRANSITION_ZONE_14, TRANSITION_ZONE_28, VERTICAL_MAPPING;
}
