package io.github.kensuke1984.anisotime;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import io.github.kensuke1984.kibrary.util.Utilities;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.nio.file.Files;

/**
 * @author Kensuke Konishi
 * @version 0.0.2
 */
public class EULA extends javax.swing.JDialog {

    /**
     * Creates new form GUITest
     */
    public EULA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        eulaScroll = new javax.swing.JScrollPane();
        eulaArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ButtonGroup acceptDecline = new ButtonGroup();
        acceptButton = new javax.swing.JRadioButton();
        declineButton = new javax.swing.JRadioButton();
        acceptDecline.add(acceptButton);
        acceptDecline.add(declineButton);
        okButton = new javax.swing.JToggleButton();
        acceptButton.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eulaArea.setColumns(20);
        eulaArea.setRows(5);
        eulaArea.setText(EULA);
        eulaArea.setLineWrap(true);
        eulaArea.setEditable(false);
        eulaArea.setCaretPosition(0);
        eulaScroll.setViewportView(eulaArea);


        eulaScroll.getVerticalScrollBar().getModel().addChangeListener(e -> {
            BoundedRangeModel m = (BoundedRangeModel) e.getSource();
            int extent = m.getExtent();
            int maximum = m.getMaximum();
            int value = m.getValue();
            if (value == 0)
                return;
            if (maximum <= value + extent)
                acceptButton.setEnabled(true);
        });

        acceptButton.setText("Accept");
        acceptButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceptButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        declineButton.setSelected(true);
        declineButton.setText("Decline");
        declineButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        okButton.setText("OK");

        okButton.addActionListener(e -> {
            if (declineButton.isSelected()) System.exit(71);
            try {
                Files.createFile(ANISOtime.AGREEMENT_PATH);
            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
            setVisible(false);
            dispose();
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(acceptButton)
                                        .addComponent(declineButton)
                                        .addComponent(okButton))
                                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acceptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(declineButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okButton)
                                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eulaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(eulaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(io.github.kensuke1984.anisotime.EULA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(io.github.kensuke1984.anisotime.EULA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(io.github.kensuke1984.anisotime.EULA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(io.github.kensuke1984.anisotime.EULA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                io.github.kensuke1984.anisotime.EULA dialog = new EULA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton acceptButton;
    private javax.swing.JRadioButton declineButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane eulaScroll;
    private javax.swing.JTextArea eulaArea;
    private javax.swing.JToggleButton okButton;

    // End of variables declaration
    static boolean isAccepted() {
        if (Files.exists(ANISOtime.AGREEMENT_PATH)) return true;
        if (GraphicsEnvironment.isHeadless()) {
            System.err.println(EULA);
            System.err.println("If you accept the terms of the agreement, type \"yes\". (yes/No)");
            try {
                String input = Utilities.readInputLine();
                if (input.equals("yes") || input.equals("Yes"))
                    return true;
                System.exit(71);
            } catch (IOException e) {
                e.printStackTrace();
            }
            System.exit(88);
        }
        EULA e = new EULA(new javax.swing.JFrame(), true);
        return true;
    }

    private static final String EULA =
            "This software (ANISOtime) is made available at no cost" +
                    " under the GNU General Public License Version 3, 29 June 2007 " +
                    "(https://www.gnu.org/licenses/)." +
                    " The GNU General Public License, gives you specific rights to use," +
                    " modify and redistribute this software." +
                    " Please be aware of section 2 of the license which specifically prevents you" +
                    " from redistributing this software incorporated, in whole or on part, into to a work," +
                    " unless that work is also covered by the GNU General Public License." +
                    " Please see the Free Software Foundation's web site for more information.\n\n" +
                    "Disclaimer: Portions of this software are copyrighted by the \"The Developers\"" +
                    " (Kensuke Konishi, Anselme F.E. Borgeaud, Kenji Kawai and Robert J. Geller, and their associates), " +
                    "and portions are also copyrighted by Sun Microsystems, Inc., Oracle Corporation, and other parties.\n\n" +
                    "The Developers have made their best efforts to produce error-free software." +
                    " If possible, the Developers will respond to questions and error reports." +
                    " HOWEVER, IN NO EVENT SHALL THE DEVELOPERS BE LIABLE TO ANY PARTY" +
                    " FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES" +
                    " ARISING OUT OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF," +
                    " EVEN IF THE DEVELOPERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE." +
                    " THE DEVELOPERS DO NOT PROMISE TO RESPOND TO QUESTIONS AND/OR ERROR REPORTS," +
                    " AND ACCEPT NO LIABILITY OR RESPONSIBILITY FOR FAILING TO DO SO.\n\n" +
                    "THE DEVELOPERS SPECIFICALLY DISCLAIM ANY WARRANTIES, INCLUDING," +
                    " BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY," +
                    " FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT." +
                    " THIS SOFTWARE IS PROVIDED ON AN \"AS IS\" BASIS," +
                    " AND THE DEVELOPERS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS," +
                    " OR MODIFICATIONS.\n\n" +
                    "Acknowledgement: Portions of the wording of this license are modified" +
                    " from the license for the Tau-P Toolkit.\n";

}
