package io.github.kensuke1984.kibrary.inversion;

public enum WeightingType {
	RECIPROCAL, LOWERUPPERMANTLE, TAKEUCHIKOBAYASHI, USERFUNCTION, IDENTITY, RECIPROCALEACHTRANSVERSE, RECIPROCAL_AZED_DPP,
	RECIPROCAL_AZED_DPP_v2
}